export const tempVehicleData = [
  {
    id: '1',
    name: 'Tesla Model 3',
    category: 'Electric',
    price: 150,
    image: 'https://images.pexels.com/photos/7553640/pexels-photo-7553640.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    available: true,
    seats: 5,
    transmission: 'automatic',
    fuelType: 'electric',
    rating: 5,
    location: 'San Francisco',
    description: 'The Tesla Model 3 is an electric four-door fastback sedan developed by Tesla. The Model 3 Standard Range Plus version delivers an EPA-rated all-electric range of 263 miles (423 km) and the Long Range versions deliver 353 miles (568 km).',
    features: [
      'Autopilot',
      'Premium Sound System',
      'Heated Seats',
      'Glass Roof',
      'Navigation',
      'Bluetooth',
      'Backup Camera',
      'Parking Sensors'
    ]
  },
  {
    id: '2',
    name: 'Range Rover Sport',
    category: 'SUV',
    price: 220,
    image: 'https://images.pexels.com/photos/116639/pexels-photo-116639.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    available: true,
    seats: 5,
    transmission: 'automatic',
    fuelType: 'diesel',
    rating: 4,
    location: 'Los Angeles',
    description: 'The Range Rover Sport is a luxury mid-size SUV produced by British car manufacturer Land Rover. The Range Rover Sport combines the luxury and capability of the larger Range Rover with a more sporty and dynamic driving experience.',
    features: [
      'All-Wheel Drive',
      'Leather Seats',
      'Navigation System',
      'Panoramic Sunroof',
      'Parking Assist',
      'Heated Seats',
      'Bluetooth',
      'Premium Sound System'
    ]
  },
  {
    id: '3',
    name: 'BMW 5 Series',
    category: 'Sedan',
    price: 180,
    image: 'https://images.pexels.com/photos/892522/pexels-photo-892522.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    available: false,
    seats: 5,
    transmission: 'automatic',
    fuelType: 'petrol',
    rating: 4,
    location: 'New York',
    description: 'The BMW 5 Series is an executive car manufactured by BMW since 1972. It is the successor to the New Class Sedans and is currently in its seventh generation. The 5 Series is BMW\'s second best-selling model after the 3 Series.',
    features: [
      'Leather Interior',
      'Navigation System',
      'Sunroof',
      'Bluetooth',
      'Heated Seats',
      'Parking Sensors',
      'Cruise Control',
      'Keyless Entry'
    ]
  },
  {
    id: '4',
    name: 'Mercedes-Benz E-Class',
    category: 'Luxury',
    price: 200,
    image: 'https://images.pexels.com/photos/4037860/pexels-photo-4037860.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    available: true,
    seats: 5,
    transmission: 'automatic',
    fuelType: 'petrol',
    rating: 5,
    location: 'Chicago',
    description: 'The Mercedes-Benz E-Class is a range of executive cars manufactured by German automaker Mercedes-Benz in various engine and body configurations. The E-Class is Mercedes-Benz\'s midrange luxury offering.',
    features: [
      'Premium Audio',
      'Leather Seats',
      'Navigation',
      'Sunroof',
      'Heated Seats',
      'Bluetooth',
      'Parking Assist',
      'Driver Assistance Package'
    ]
  },
  {
    id: '5',
    name: 'Audi Q5',
    category: 'SUV',
    price: 190,
    image: 'https://images.pexels.com/photos/1035108/pexels-photo-1035108.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    available: true,
    seats: 5,
    transmission: 'automatic',
    fuelType: 'diesel',
    rating: 4,
    location: 'San Francisco',
    description: 'The Audi Q5 is a series of compact luxury crossover SUVs produced by the German luxury car manufacturer Audi. The original first-generation model was the third member of the B8 family to be released after the Audi A5 and fourth-generation A4.',
    features: [
      'Quattro All-Wheel Drive',
      'Leather Interior',
      'Panoramic Sunroof',
      'Navigation',
      'Bluetooth',
      'Parking Sensors',
      'Heated Seats',
      'Keyless Entry'
    ]
  },
  {
    id: '6',
    name: 'Toyota Camry',
    category: 'Sedan',
    price: 120,
    image: 'https://images.pexels.com/photos/10894580/pexels-photo-10894580.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    available: true,
    seats: 5,
    transmission: 'automatic',
    fuelType: 'petrol',
    rating: 4,
    location: 'Dallas',
    description: 'The Toyota Camry is an automobile sold internationally by the Japanese manufacturer Toyota since 1982, spanning multiple generations. The Camry has been the best-selling passenger car in the United States.',
    features: [
      'Bluetooth',
      'Backup Camera',
      'Lane Departure Warning',
      'Adaptive Cruise Control',
      'Apple CarPlay',
      'Android Auto',
      'Keyless Entry',
      'Push Button Start'
    ]
  },
  {
    id: '7',
    name: 'Porsche 911',
    category: 'Luxury',
    price: 350,
    image: 'https://images.pexels.com/photos/3752169/pexels-photo-3752169.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    available: true,
    seats: 2,
    transmission: 'automatic',
    fuelType: 'petrol',
    rating: 5,
    location: 'Miami',
    description: 'The Porsche 911 is a two-door, 2+2 high performance rear-engined sports car made since 1963 by Porsche AG of Stuttgart, Germany. It has a rear-mounted flat-six engine and all round independent suspension.',
    features: [
      'Sport Exhaust System',
      'Sport Chrono Package',
      'Leather Interior',
      'Navigation',
      'Bluetooth',
      'Premium Sound System',
      'Heated Seats',
      'Parking Sensors'
    ]
  },
  {
    id: '8',
    name: 'Chevrolet Suburban',
    category: 'SUV',
    price: 230,
    image: 'https://images.pexels.com/photos/2676096/pexels-photo-2676096.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    available: false,
    seats: 8,
    transmission: 'automatic',
    fuelType: 'petrol',
    rating: 3,
    location: 'Houston',
    description: 'The Chevrolet Suburban is a full-size, extended-length SUV from Chevrolet. It is the longest continuous use automobile nameplate in production, starting in 1935 for the 1935 U.S. model year.',
    features: [
      'Third Row Seating',
      'Large Cargo Space',
      'Towing Package',
      'Navigation',
      'Bluetooth',
      'Backup Camera',
      'Apple CarPlay',
      'Android Auto'
    ]
  },
  {
    id: '9',
    name: 'Nissan Leaf',
    category: 'Electric',
    price: 130,
    image: 'https://images.pexels.com/photos/13861/IMG_3496bfree.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    available: true,
    seats: 5,
    transmission: 'automatic',
    fuelType: 'electric',
    rating: 4,
    location: 'Seattle',
    description: 'The Nissan Leaf is a compact five-door hatchback battery electric vehicle manufactured by Nissan. It was introduced in Japan and the United States in December 2010, and it is currently in its second generation.',
    features: [
      'Electric Powertrain',
      'Navigation',
      'Bluetooth',
      'Backup Camera',
      'Apple CarPlay',
      'Android Auto',
      'Heated Seats',
      'Keyless Entry'
    ]
  },
  {
    id: '10',
    name: 'Honda CR-V',
    category: 'SUV',
    price: 140,
    image: 'https://images.pexels.com/photos/10804576/pexels-photo-10804576.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    available: true,
    seats: 5,
    transmission: 'automatic',
    fuelType: 'petrol',
    rating: 4,
    location: 'Denver',
    description: 'The Honda CR-V is a compact crossover SUV manufactured by Honda since 1995 and introduced in the North American market in 1997. It uses the Honda Civic platform with an SUV body design.',
    features: [
      'All-Wheel Drive',
      'Backup Camera',
      'Bluetooth',
      'Apple CarPlay',
      'Android Auto',
      'Heated Seats',
      'Moonroof',
      'Keyless Entry'
    ]
  }
];